language: node_js
node_js:
- "7"
- "6"
before_install:
- npm install
install:
- npm run bootstrap
script:
- npm test
- npm run build
after_success:
- echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> ~/.npmrc
- npm run ci-publish