language: node_js
node_js:
- '6'
before_install:
- npm install
install:
- npm run bootstrap
script:
- npm test
- npm run build
deploy:
  skip_cleanup: true
after_success:
- sh ./npm-login.sh
- npm run ci-publish