environment:
  nodejs_version: "6"
install:
  - ps: Install-Product node 6
  - npm install
  - npm run bootstrap
test_script:
  - node --version
  - npm --version
  - npm test
  - npm run build
build: off